# Generated by Django 5.2.7 on 2025-10-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_statistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='value',
            field=models.BigIntegerField(default=0, help_text='Enter a whole number. Commas are allowed (e.g. 10,000).'),
        ),
    ]
